### PR TITLE
Documentation is now on branch 'gh-pages'

### PR DESCRIPTION
**Pull request by golaz**
ACME Diags documentation is now maintained with Sphinx and kept on its own 
separate branch ('gh-pages') so that it can be served directly from github.io.

### CODE REVIEW

**Comment by zshaheen** [comment]
This PR deletes some file in `docs` which are used in the viewer.
I'll merge after we release, since these are changes that will require some testing.

**Comment by golaz** [comment]
@zshaheen : I did not realize some files were needed by the viewer; just put the needed files back in `docs`. But we should not have a release with documentation in multiple places.

**Comment by zshaheen** [comment]
@golaz Hmmm, okay. I'll take care of that.

**Comment by zshaheen** [comment]
All of this is already done on master.

**Pull request closed without merging**
