### PR TITLE
Cosp histgram

### PR DESCRIPTION
**Pull request by chengzhuzhang**
Adding a new set of diagnostics to compare cloud fraction between model and satellite observed though COSP simulator, so that the comparison is apple to apple.

### CODE REVIEW

**Comment by doutriaux1** [comment]
no vcs :(

**Comment by chengzhuzhang** [comment]
Will add later. Here is an example, 
isccpcosp-cosp_histogram_isccp-ann-global
Since Dean tasked Jonathas to enhance vcs, can I contact him for a template?

**Comment by doutriaux1** [comment]
@chengzhuzhang I talked about this weeks ago with @zshaheen he knows what to do. It's basically a boxfill really. Just use templates to draw the boxes. BTW I don't think it's an histogram. Histograms are more lime this: https://www.google.com/search?q=histogram&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiyq9_Y08XVAhUlzoMKHZ-zDKwQ_AUICigB&biw=1284&bih=850&dpr=2

**Comment by chengzhuzhang** [comment]
@doutriaux1 yeah, its actually 2d joint histogram, I just call it histogram for short...

**Pull request merged**
